name: my_multi_tools
description: A multi-platform application with various tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  video_player: ^2.8.1
  path_provider: ^2.1.2
  intl: 0.20.2
  video_thumbnail: ^0.5.3
  media_info: 0.12.0+2
  ffmpeg_kit_flutter: ^6.0.3
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true